### ISSUE TITLE
All Metrics related API should be accessible with Connected App Credentials

### ISSUE THREAD

**Issue by rjsp-cg** [mulesoft-catalyst/metrics-toolkit#147]
At our organization, we cannot use Org admin username and password in an application. We are not able to adopt this tool because of this gap and limitation.
According to the limitations section in the following link
https://github.com/mulesoft-catalyst/metrics-accelerator,
API Platform Client Applications metrics and analytics Metrics are not supported when authenticating with Connected Apps.

It requires an user with Org admin role credentials which is not possible in our security domain. Metrics API should also be able to be accessible with connected app credentials.

**Comment by richardmckinley** [comment]
Hi @rajcg, 
The limitations around what connected apps can be used for are related to how the platform APIs are implemented, rather than the metrics toolkit. 
If you think connected app support should be increased for the platform APIs you can raise an idea in the [MuleSoft ideas portal](https://help.mulesoft.com/s/ideas).  
I am going to mark this issue as closed but fee free to re-open with any additional details or queries. 
Thanks and regards, 
Richard
