### ISSUE TITLE
API Instance count is not correct

### ISSUE THREAD

**Issue by saurabhgoyalgithub** [mulesoft-catalyst/metrics-toolkit#152]
Total API instance count for an environment is different from the actual count. This also differs from the API instance count returned from AnyPoint Platform APIs.

**Comment by richardmckinley** [comment]
Hi @saurabhgoyalgithub 
Can you please elaborate on where you are seeing these discrepancies? Is it in a particular dashboard etc.? 
Screenshots of your platform API response compared to the metrics-toolkit output would be helpful as well. 
Thanks and regards, 
Richard

**Comment by saurabhgoyalgithub** [comment]
Hi @richardmckinley ,

Our CSM Aaron has shared required information to you separately. Please let me know if further details are needed.
Appreciate your prompt attention to this!

Thanks,
Saurabh

**Comment by richardmckinley** [comment]
Hi @saurabhgoyalgithub, 
I believe Aaron has already shared the details with you but wanted to respond here for future reference. 

The field apiManagerMetrics.apis.{environment}.total refers to the total number of API specs managed in the environment. It is listed under the available metrics table in the [README](https://github.com/mulesoft-catalyst/metrics-toolkit/blob/e62ec39dcb8ee9c015c29a2156a01fe88381d4c0/README.md?plain=1#L108)
The field $.apiManagerMetrics.apis.{environment}.apiInstances is the total count of all API instances. Each API spec can have many managed instances, which is why this count is greater. 
The active and inactive count should total the total instance count. 

I understand how this can be confusing due to the naming. This is how the fields are named in the platform API and the same was used in the metrics toolkit. Changing the names of these fields would introduce breaking changes to the toolkit, so we will not be changing the names right now. 

Hopefully this helps to clarify. If you have further questions, or notice discrepancies in these counts please do let us know. 
Thanks and regards, 
Richard
