### ISSUE TITLE
API Clients  (API Client Applications) in Access management Dashboard 

### ISSUE THREAD

**Issue by JanakiSaranyaGit** [mulesoft-catalyst/metrics-toolkit#87]
API Client application flow (which pushes data to Access Management splunk dashboard)   gets the applications under RuntimeManager which looks incorrect . Please advise API Clients refers to the Client Providers in Access Management or Client Applications in API manager

**Comment by olamiral-mulesoft** [comment]
API Clients refers to client applications that consume APIs and this information is collected from using the API Platform api. Could you please provide additional information explaining how you've identified that the API Client Applications stats are being collected from Runtime Manager instead of API Platform? Thank you?

**Comment by panizzag** [comment]
Hi @JanakiSaranyaGit Have you had the chance to look at the question posted by Olivier?
Please, respond if you have the chance. We'll wait some more time before closing this issue.

Thanks!
Gaston

**Comment by richardmckinley** [comment]
Hi @JanakiSaranyaGit,
I am going to mark this issue as closed for now. If you would like to re-open it please leave a new comment and tag me in your response. 
Thanks and regards, 
Richard
